insert into course values
    ("02LSEOV", "Computer architectures" ,12, NULL, NULL),
    ("01SQJOV", "Data Science and Database Technology", 8, NULL,NULL) ,
    ("01SQMOV", "Data Science e Tecnologie per le Basi di Dati" ,8, NULL, NULL),
    ("01SQLOV" ,"Database systems", 8, null,null),
    ("01OTWOV" ,"Computer network technologies and services", 6, 3,null),
    ("02KPNOV", "Tecnologie e servizi di rete", 6 ,3,null),
    ("01TYMOV", "Information systems security services", 12,null,null),
    ("01UDUOV", "Sicurezza dei sistemi informativi", 12,null,null),
    ("05BIDOV", "Ingegneria del software ",6,NULL,"02GOLOV"),
    ("04GSPOV" ,"Software engineering", 6,NULL,"02LSEOV"),
    ("01UDFOV" ,"Applicazioni Web I",6,null,null),
    ("01TXYOV" ,"Web Applications I ",6 ,3,null),
    ("01TXSOV", "Web Applications II", 6,NULL,"01TXYOV"),
    ("02GRSOV" ,"Programmazione di sistema" ,6,null,null),
    ("01NYHOV" ,"System and device programming", 6 ,3,null),
    ("01SQOOV", "Reti Locali e Data Center", 6,null,null),
    ("01TYDOV" ,"Software networking ",7,null,null),
    ("03UEWOV", "Challenge", 5, null,null),
    ("01URROV", "Computational intelligence", 6,null,null),
    ("01OUZPD", "Model based software design", 4, null,null),
    ("01URSPD" ,"Internet Video Streaming" ,6 ,2,null);

    insert into incompatibility values
    ("02GOLOV","02LSEOV"),
    ("02LSEOV","02GOLOV"),
    ("01SQJOV","01SQMOV"),
    ("01SQJOV","01SQLOV"),
    ("01SQMOV","01SQJOV"),
    ("01SQMOV","01SQLOV"),
    ("01SQLOV","01SQJOV"),
    ("01SQLOV","01SQMOV"),
    ("01OTWOV","02KPNOV"),
    ("02KPNOV","01OTWOV"),
    ("01TYMOV","01UDUOV"),
    ("01UDUOV","01TYMOV"),
    ("05BIDOV","04GSPOV"),
    ("04GSPOV","05BIDOV"),
    ("01UDFOV","01TXYOV"),
    ("01TXYOV","01UDFOV"),
    ("02GRSOV","01NYHOV"),
    ("01NYHOV","02GRSOV");
   